fn main() {
    // Generate C header using cbindgen when building the crate.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    // Write header to crate root for easier consumption
    let header_path = std::path::Path::new(&crate_dir).join("vlfd_ffi.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        usize_is_size_t: true,
        cpp_compat: true,
        no_includes: false,
        header: Some(String::from("// Auto-generated by cbindgen. Do not edit.")),
        include_guard: Some(String::from("CBINDGEN__VLFD_FFI_H")),
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(header_path);
}
